### ISSUE TITLE
v0.3.6 breaks listeners

### ISSUE THREAD

**Issue by grindlemire** [benjeffery/react-plotlyjs#12]
The `newPlot` call in `componentDidUpdate` introduced in v0.3.6 removes the old event listeners whenever `componentDidUpdate` is called. It may be that Plotly does some amount of mangling to the container which removes the listeners.

 In the short term it can be fixed by reapplying all the listeners every update but I am unsure of how it should be done in the long term

**Comment by benjeffery** [comment]
Thanks, an oversight on my part. This project needs tests!

**Comment by benjeffery** [comment]
Fixed in v0.3.7.
