### ISSUE TITLE
Importing plotly-cartesian

### ISSUE THREAD

**Issue by athenawisdoms** [benjeffery/react-plotlyjs#15]
How should we import the `plotly-cartesian` module into a Meteor app?

    import Plotly from 'plotly.js/dist/plotly-cartesian';

does not work because it gives an error 

    Uncaught Error: Cannot find module 'plotly.js/dist/plotly-cartesian'

Is there a way to save it using something like `npm install package-name --save`?

Did not find these modules via `npm search plotly`

**Comment by tamaccount** [comment]
I have the same question.  Please include Install directions.

**Comment by tamaccount** [comment]
@athenawisdoms 

I figured out our problem. We npm installed `plotly` when we should have installed `plotly.js`.
https://www.javascripting.com/view/plotly-js

Once you run`npm install plotly.js`, `import Plotly from 'plotly.js/dist/plotly-cartesian'` should work just fine.
