### ISSUE TITLE
react-plotlyjs with typescript issue

### ISSUE THREAD

**Issue by mhmoudgmal** [benjeffery/react-plotlyjs#9]
error TS2604: JSX element type 'Plotly' does not have any construct or call signatures.

**Comment by mhmoudgmal** [comment]
when I use import 
`import { Plotly } from "react-plotlyjs"`
It display that error, and it does not display the chart.

But when I use require 
`const Plotly = require('react-plotlyjs');`

it throws the same error , but it displays the chart at least.

**Comment by benjeffery** [comment]
I am not familiar with TypeScript - and without a minimal test case that displays the error I can't start to debug. Are you sure this is an issue with react-plotlyjs?

**Comment by benjeffery** [comment]
I'm going to close this issue, re-open it if you find this module to be the problem.
